ktor:
    application:
        modules:
            - pl.msiwak.ApplicationKt.module
    deployment:
        port: 8080
storage:
    jdbcURL: "jdbc:postgresql://database:5432/postgres"
    user: "postgres"
    password: "password"
